-- =======================================================
-- SQL SCRIPT CẤU HÌNH DATABASE CHO ROOMCHAT (PRODUCTIONS-READY)
-- Copy toàn bộ nội dung script này và chạy trong SQL Editor của Supabase Dashboard
-- =======================================================

-- Xóa sạch các bảng cũ để tránh xung đột kiểu dữ liệu (bigint vs uuid)
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.rooms CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 1. TẠO BẢNG PROFILES (Đồng bộ thông tin công khai từ auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    avatar_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Bật Row Level Security (RLS) cho bảng profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 2. TẠO BẢNG ROOMS (Phòng chat)
CREATE TABLE IF NOT EXISTS public.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    created_by UUID REFERENCES auth.users ON DELETE SET NULL
);

-- Bật RLS cho bảng rooms
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;

-- 3. TẠO BẢNG MESSAGES (Tin nhắn)
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT REFERENCES public.rooms ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Bật RLS cho bảng messages
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;


-- =======================================================
-- TRIGGERS & FUNCTIONS TỰ ĐỘNG
-- =======================================================

-- Hàm tự động cập nhật thời gian updated_at
CREATE OR REPLACE FUNCTION public.handle_update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER on_profile_updated
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE PROCEDURE public.handle_update_timestamp();

-- Hàm trigger tự động tạo Profile khi có User đăng ký mới trong auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, username, avatar_url)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'username', 'user_' || SUBSTR(NEW.id::text, 1, 8)),
        COALESCE(NEW.raw_user_meta_data->>'avatar_url', 'https://api.dicebear.com/7.x/adventurer/svg?seed=' || NEW.id)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger chạy sau khi chèn user vào auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- =======================================================
-- ĐỊNH NGHĨA CHÍNH SÁCH BẢO MẬT (RLS POLICIES)
-- =======================================================

-- ** Bảng Profiles **
-- Cho phép mọi user (cả chưa đăng nhập) xem thông tin profile của người khác (để hiển thị username/avatar trong chat)
CREATE POLICY "Cho phép xem profiles công khai" 
    ON public.profiles FOR SELECT 
    USING (true);

-- Chỉ cho phép chính user đó cập nhật profile của mình
CREATE POLICY "Chỉ cho phép cập nhật profile chính chủ" 
    ON public.profiles FOR UPDATE 
    USING (auth.uid() = id);

-- ** Bảng Rooms **
-- Cho phép user đã đăng nhập được xem danh sách phòng
CREATE POLICY "Cho phép đọc danh sách phòng khi đã đăng nhập" 
    ON public.rooms FOR SELECT 
    USING (auth.role() = 'authenticated');

-- Cho phép user đã đăng nhập được tạo phòng mới
CREATE POLICY "Cho phép tạo phòng mới khi đã đăng nhập" 
    ON public.rooms FOR INSERT 
    WITH CHECK (auth.role() = 'authenticated');

-- ** Bảng Messages **
-- Cho phép user đã đăng nhập xem tin nhắn
CREATE POLICY "Cho phép xem tin nhắn khi đã đăng nhập" 
    ON public.messages FOR SELECT 
    USING (auth.role() = 'authenticated');

-- Chỉ cho phép user đã đăng nhập gửi tin nhắn dưới danh nghĩa của chính họ
CREATE POLICY "Chỉ cho phép gửi tin nhắn chính chủ" 
    ON public.messages FOR INSERT 
    WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = user_id);


-- =======================================================
-- DỮ LIỆU THỬ NGHIỆM BAN ĐẦU (SEED DATA - OPTIONAL)
-- =======================================================
INSERT INTO public.rooms (name) VALUES 
('Phòng Chat Chung 💬'),
('Thảo Luận ReactJS ⚛️'),
('Supabase & Backend ⚡')
ON CONFLICT DO NOTHING;

-- =======================================================
-- KÍCH HOẠT TÍNH NĂNG REALTIME CHO CÁC BẢNG
-- =======================================================
-- Thêm các bảng vào danh sách phát tin hiệu Realtime của Supabase
ALTER PUBLICATION supabase_realtime ADD TABLE public.rooms;
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;

-- =======================================================
-- BỔ SUNG CHÍNH SÁCH BẢO MẬT UPDATE/DELETE CHO BẢNG ROOMS
-- =======================================================
DROP POLICY IF EXISTS "Chủ phòng được sửa phòng" ON public.rooms;
CREATE POLICY "Chủ phòng được sửa phòng" 
    ON public.rooms FOR UPDATE 
    USING (auth.role() = 'authenticated' AND auth.uid() = created_by);

DROP POLICY IF EXISTS "Chủ phòng được xóa phòng" ON public.rooms;
CREATE POLICY "Chủ phòng được xóa phòng" 
    ON public.rooms FOR DELETE 
    USING (auth.role() = 'authenticated' AND auth.uid() = created_by);


-- =======================================================
-- CẤU HÌNH STORAGE BUCKET CHO AVATARS (LƯU TRỮ ẢNH)
-- =======================================================
-- Tự động chèn tạo bucket 'avatars' công khai nếu chưa tồn tại
INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Policy 1: Cho phép mọi người đọc ảnh avatar công khai
DROP POLICY IF EXISTS "Cho phép đọc avatar công khai" ON storage.objects;
CREATE POLICY "Cho phép đọc avatar công khai" 
    ON storage.objects FOR SELECT 
    USING (bucket_id = 'avatars');

-- Policy 2: Chỉ cho phép user đã đăng nhập upload ảnh đại diện
DROP POLICY IF EXISTS "Cho phép upload avatar khi đã đăng nhập" ON storage.objects;
CREATE POLICY "Cho phép upload avatar khi đã đăng nhập" 
    ON storage.objects FOR INSERT 
    WITH CHECK (bucket_id = 'avatars' AND auth.role() = 'authenticated');

-- Policy 3: Cho phép user cập nhật/xóa avatar của mình
DROP POLICY IF EXISTS "Cho phép cập nhật avatar chính chủ" ON storage.objects;
CREATE POLICY "Cho phép cập nhật avatar chính chủ" 
    ON storage.objects FOR UPDATE 
    USING (bucket_id = 'avatars' AND auth.role() = 'authenticated');


