-- =======================================================
-- SQL SCRIPT NÂNG CẤP DATABASE HỖ TRỢ PHÒNG CHAT RIÊNG TƯ (PRIVATE ROOMS)
-- Copy toàn bộ nội dung script này và chạy trong SQL Editor của Supabase Dashboard
-- =======================================================

-- 1. Bổ sung cột is_private vào bảng rooms (Mặc định là FALSE để tương thích ngược với phòng cũ)
ALTER TABLE public.rooms 
ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT FALSE;

-- Đảm bảo các phòng cũ (nếu có) có giá trị FALSE thay vì NULL để tránh bị ẩn do RLS policy
UPDATE public.rooms 
SET is_private = FALSE 
WHERE is_private IS NULL;

-- 2. Tạo bảng liên kết thành viên phòng chat (room_members)
CREATE TABLE IF NOT EXISTS public.room_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT REFERENCES public.rooms ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles ON DELETE CASCADE NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE (room_id, user_id)
);

-- Kích hoạt Row Level Security (RLS) cho bảng room_members
ALTER TABLE public.room_members ENABLE ROW LEVEL SECURITY;

-- 3. Cấu hình các chính sách bảo mật (RLS Policies) mới

-- Bảng rooms: Đọc phòng (Chỉ cho phép đọc phòng Public hoặc phòng Private mà user là thành viên hoặc chủ phòng)
DROP POLICY IF EXISTS "Cho phép đọc danh sách phòng khi đã đăng nhập" ON public.rooms;
DROP POLICY IF EXISTS "Đọc phòng Public hoặc Private được mời" ON public.rooms;
DROP POLICY IF EXISTS "Đọc phòng Public công khai" ON public.rooms;
DROP POLICY IF EXISTS "Đọc phòng Private được mời" ON public.rooms;

-- Policy 1: Cho phép đọc tất cả phòng Public công khai (Không lồng bảng để tránh lỗi chéo bảng cho request anonymous)
CREATE POLICY "Đọc phòng Public công khai" 
    ON public.rooms FOR SELECT 
    USING (is_private = FALSE);

-- Policy 2: Chỉ cho phép đọc phòng Private nếu user đã đăng nhập và là chủ phòng hoặc được mời
CREATE POLICY "Đọc phòng Private được mời" 
    ON public.rooms FOR SELECT 
    USING (
        auth.uid() IS NOT NULL AND 
        is_private = TRUE AND (
            created_by = auth.uid() OR 
            EXISTS (
                SELECT 1 FROM public.room_members 
                WHERE room_members.room_id = rooms.id AND room_members.user_id = auth.uid()
            )
        )
    );

-- Bảng rooms: Cập nhật chính sách INSERT/UPDATE/DELETE của bảng rooms để đồng bộ dùng auth.uid()
DROP POLICY IF EXISTS "Cho phép tạo phòng mới khi đã đăng nhập" ON public.rooms;
CREATE POLICY "Cho phép tạo phòng mới khi đã đăng nhập" 
    ON public.rooms FOR INSERT 
    WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Chủ phòng được sửa phòng" ON public.rooms;
CREATE POLICY "Chủ phòng được sửa phòng" 
    ON public.rooms FOR UPDATE 
    USING (auth.uid() = created_by);

DROP POLICY IF EXISTS "Chủ phòng được xóa phòng" ON public.rooms;
CREATE POLICY "Chủ phòng được xóa phòng" 
    ON public.rooms FOR DELETE 
    USING (auth.uid() = created_by);

-- Bảng messages: Chỉ cho xem tin nhắn của phòng mà user có quyền truy cập
DROP POLICY IF EXISTS "Cho phép xem tin nhắn khi đã đăng nhập" ON public.messages;
DROP POLICY IF EXISTS "Xem tin nhắn phòng được phép truy cập" ON public.messages;
CREATE POLICY "Xem tin nhắn phòng được phép truy cập" 
    ON public.messages FOR SELECT 
    USING (
        auth.uid() IS NOT NULL AND 
        EXISTS (
            SELECT 1 FROM public.rooms 
            WHERE rooms.id = room_id
        )
    );

-- Bảng messages: Chỉ cho gửi tin nhắn vào phòng mà user có quyền truy cập dưới danh nghĩa chính mình
DROP POLICY IF EXISTS "Chỉ cho phép gửi tin nhắn chính chủ" ON public.messages;
DROP POLICY IF EXISTS "Gửi tin nhắn vào phòng được phép truy cập" ON public.messages;
CREATE POLICY "Gửi tin nhắn vào phòng được phép truy cập" 
    ON public.messages FOR INSERT 
    WITH CHECK (
        auth.uid() IS NOT NULL AND 
        auth.uid() = user_id AND
        EXISTS (
            SELECT 1 FROM public.rooms 
            WHERE rooms.id = room_id
        )
    );

-- Bảng room_members: Phân quyền xem và quản lý thành viên
-- Cho phép SELECT tự do bảng room_members để tránh lỗi phân quyền RLS chéo bảng đối với request anonymous
DROP POLICY IF EXISTS "Xem thành viên của phòng được phép" ON public.room_members;
CREATE POLICY "Xem thành viên của phòng được phép" 
    ON public.room_members FOR SELECT 
    USING (true);

-- Chỉ chủ phòng (người tạo phòng) mới được quyền Mời thành viên (INSERT) hoặc Xóa thành viên (DELETE)
-- Tách riêng biệt INSERT/DELETE thay vì dùng FOR ALL để tránh Postgres tự động áp dụng đè lên SELECT gây đệ quy vòng tròn RLS
DROP POLICY IF EXISTS "Chủ phòng quản lý thành viên" ON public.room_members;
DROP POLICY IF EXISTS "Chủ phòng quản lý thành viên INSERT" ON public.room_members;
DROP POLICY IF EXISTS "Chủ phòng quản lý thành viên DELETE" ON public.room_members;

CREATE POLICY "Chủ phòng quản lý thành viên INSERT" 
    ON public.room_members FOR INSERT 
    WITH CHECK (
        auth.uid() IS NOT NULL AND 
        EXISTS (
            SELECT 1 FROM public.rooms 
            WHERE rooms.id = room_id AND rooms.created_by = auth.uid()
        )
    );

CREATE POLICY "Chủ phòng quản lý thành viên DELETE" 
    ON public.room_members FOR DELETE 
    USING (
        auth.uid() IS NOT NULL AND 
        EXISTS (
            SELECT 1 FROM public.rooms 
            WHERE rooms.id = room_id AND rooms.created_by = auth.uid()
        )
    );

-- 4. Kích hoạt tính năng phát Realtime cho bảng room_members (Chạy kiểm tra an toàn tránh lỗi chạy lại)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'room_members'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.room_members;
    END IF;
END $$;

-- 5. Tạo mặc định một phòng chung cho cộng đồng (Phòng Public)
-- Sử dụng WHERE NOT EXISTS để tránh tạo trùng lặp khi chạy lại file script
INSERT INTO public.rooms (name, is_private)
SELECT 'Phòng Cộng Đồng 🌐', false
WHERE NOT EXISTS (
    SELECT 1 FROM public.rooms WHERE name = 'Phòng Cộng Đồng 🌐'
);
